### ISSUE TITLE
Service Request by Anna N. Weiskopf about Milestone data sorting

### ISSUE THREAD

**Issue by dlounsbu** [dlounsbu/NYHEALing-IPAtracker-support#10]
- [x] e-mail acknowledging that User's request was received
- [x] Problem PARTIALLY RESOLVED 
- [ ] Problem FULLY RESOLVED and Issue is Closed
- [x] Post-Service Request Survey was sent to User

Use comments feature (below) to document:

1. A clear and concise description of the solution.

2. A clear and concise description of any alternative solutions or features you've considered.

3. Any additional context, such as screenshots about the problem.

**Comment by dlounsbu** [comment]
From: Anna N. Weiskopf [mailto:aw3391@columbia.edu] 
Sent: Wednesday, August 11, 2021 2:30 PM
To: Donrie Purcell <donrie.purcell@einsteinmed.org>; david lounsbury <david.lounsbury@einsteinmed.org>; Nicholas Bove <nicholas.bove@einsteinmed.org>; Anika Buch <ambuch@princeton.edu>
Cc: Nasim Sabounchi <Nasim.Sabounchi@sph.cuny.edu>; Emma Rodgers <emr2241@columbia.edu>
Subject: Questions about IPA tracker

CAUTION: This email comes from an external source; the attachments and/or links may compromise our secure environment. Do not open or click on suspicious emails. Please click on the “Phish Alert” button on the top right of the Outlook dashboard to report any suspicious emails.
Hi Donrie,

Nasim and I were reviewing Cayuga in the IPA tracker and had a few questions.
•	Is there a way to sort the measures, milestones, etc. by 1 IPA strategy specifically under monitoring? For example, Cayuga's MOUD Expansion B1 IPA has 5 strategies listed (B1-EP, B1-ER, etc.) and when IPA monitoring is selected, it lists the monitoring measures for all 5 strategies, rather than 1 at a time. 
•	Is there a way to sort milestones by date, alphabetically, by person responsible, etc. under strategy specifications? 
•	What is the difference between feedback/QI under monitoring vs under strategy specifications? Where should updated information be entered into?
•	Where should county staff put discontinued IPAs? 
Thank you for your help and let me know if you have any questions.

Best,
Anna

-- 
Anna Weiskopf, MPA
Research Coordinator
Social Intervention Group, HEALing Communities Study
Columbia University School of Social Work
1255 Amsterdam Avenue, Suite 807
New York, NY 10027
Email: aw3391@columbia.edu
Cell: 212-853-7053 
Website: https://sig.columbia.edu/

**Comment by dlounsbu** [comment]
From: david lounsbury 
Sent: Wednesday, August 11, 2021 4:56 PM
To: Anna N. Weiskopf <aw3391@columbia.edu>; Donrie Purcell <donrie.purcell@einsteinmed.org>; Nicholas Bove <nicholas.bove@einsteinmed.org>; Anika Buch <ambuch@princeton.edu>
Cc: Nasim Sabounchi <Nasim.Sabounchi@sph.cuny.edu>; Emma Rodgers <emr2241@columbia.edu>
Subject: RE: Questions about IPA tracker
Importance: High

Hi Anna:

Just chiming in here. 

In general, in the Tracker, information entered should be ordered by date (if there is a date field). Otherwise, it presents in the order it was entered. 

But if you want to sort things otherwise, I recommend that you download the data you are interested in, and sort/tabulate/graph it that way. What you want to do with Milestones would be easy to do by downloading the data. 

Feedback/QI under SPECIFICATION is at the level of the STRATEGY. Feedback/QI in Monitoring is at the level of the IPA.

I would keep a discontinued IPA in the system, but mark it as Discontinued or Stopped in Milestone MONITORING, or whatever the label is. We can add labels to Milestone Status, if need be. 

I very much like that you are posing these questions and trying things out. To help us respond quickly to and to manage requests, we created this quick reference site: https://github.com/dlounsbu/NYHEALing-IPAtracker-support

Next time, please bookmark it and try out the Request Service link for us.

Best and thanks,
David

**Comment by dlounsbu** [comment]
Hi Donrie: 

Anything to add here, or can we close this issue for Anna?

DL

**Comment by dlounsbu** [comment]
From: Donrie Purcell 
Sent: Wednesday, August 11, 2021 5:04 PM
To: Anna N. Weiskopf <aw3391@columbia.edu>; david lounsbury <david.lounsbury@einsteinmed.org>; Nicholas Bove <nicholas.bove@einsteinmed.org>; Anika Buch <ambuch@princeton.edu>
Cc: Nasim Sabounchi <Nasim.Sabounchi@sph.cuny.edu>; Emma Rodgers <emr2241@columbia.edu>
Subject: Re: Questions about IPA tracker

Hi Anna,

I will do my best to address the questions:

1.	As far as I know the IPA tracker does not allow you to sort the data much the way you would (for example) in an excel spreadsheet. However, when the data is downloaded it does so in an excel file format and sorting can be done from there. (I suspect that does not help you because you may not be interested in data analytics but rather making sense of things visually in front of you). Additionally, I can see what you’re referring to in terms monitoring only the strategy that is of interest to you at any particular point in time. Allow me the opportunity to discuss this with Dr. Lounsbury and see if this can be remedied to make this process easier.  I don’t know what Dr. Lounsbury’s perspective is on this as we previously discussed having Measures, Milestones, etc. sorted by date according to the history. 
2.	Ideally, all Milestones should be sorted by date in the tracker. If otherwise, let us meet with Dr. Lounsbury as soon as you can so we can discuss further. 
3.	In terms of Feedback/QI for Specification- when you’re specifying a smart strategy under an IPA, ideally one is in the planning stage and as such the community collation member will want to speak with the coach to get feedback on the merits of the strategy, etc. Now, in terms of monitoring, we suspect that even after the IPA and the strategy has been approved by the coalition and HCS Members, things are constantly changing and even more so when the strategy may need adjustment this in itself a function of monitoring between the coach and community coalition, which will require some form of feedback. I see Dr. Hunt and Derek consistently engaging in continuous feedback on the merits of strategies already deployed within the communities. Please view these smart strategies as pieces on a chessboard that are Monitored and given constructive feedback from time to time.
4.	In terms of discontinued IPA’s, Now that’s an interesting one. While this is a question for Dr. Hunt, Dr. Lounsbury, Emma, the coaches and so forth. I do believe that within the Monitoring of Challenges some form of documentation (qualitative assessment) will tell you that an IPA is discontinued and the data will reflect same.

Anna and Nasim, I hope that I was of help.
Anna please draft/document these concerns in the system set up by Dr. Lounsbury so he can keep track with the contractor of the database. 
And don’t be coy about asking any question or questions about the IPA tracker. That what I am here for, to offer consistent and clear support to you and the team on a whole.

https://github.com/dlounsbu/NYHEALing-IPAtracker-support
To make a request for support, please click here:
https://einsteinmed.co1.qualtrics.com/jfe/form/SV_4TvKdfrpwnbgBrE
 
Regards
Donrie Purcell, PhD, MPH

**Comment by dlounsbu** [comment]
@donriepurcell : Just added your very excellent reply to Anna, here, for the Issue card thread!

**Comment by dlounsbu** [comment]
From: david lounsbury 
Sent: Wednesday, August 11, 2021 5:27 PM
To: Anna N. Weiskopf <aw3391@columbia.edu>
Cc: Donrie Purcell <donrie.purcell@einsteinmed.org>; Nicholas Bove <nicholas.bove@einsteinmed.org>; Anika Buch <ambuch@princeton.edu>; Nasim Sabounchi <Nasim.Sabounchi@sph.cuny.edu>; Emma Rodgers <emr2241@columbia.edu>
Subject: RE: Questions about IPA tracker

Hi Anna:

Unless I am not following you, when you EDIT a SPECIFIED Strategy, you only see information for that strategy. You have to navigate to different components,  of course, to see all that has been entered. 

When you switch to IPA MONITORING, then you see all the reported data for all the components of all the SPECIFIED Strategies for that IPA. Once you enter all prompted MONITORING data, at the bottom part of the screen you will see that the MONITORING data is ordered by Reporting Period. 

And, again, we can help you download the data so that you can sort, filter, tabulate or graph information the way you need/want. 

Hope this helps! 

Best,
David

**Comment by dlounsbu** [comment]
From: david lounsbury 
Sent: Wednesday, August 11, 2021 6:29 PM
To: Anna N. Weiskopf <aw3391@columbia.edu>
Cc: Donrie Purcell <donrie.purcell@einsteinmed.org>; Nicholas Bove <nicholas.bove@einsteinmed.org>; Anika Buch <ambuch@princeton.edu>; Nasim Sabounchi <Nasim.Sabounchi@sph.cuny.edu>; Emma Rodgers <emr2241@columbia.edu>
Subject: RE: Questions about IPA tracker

Hi Anna:

I think I understand more about what you are asking now. I think it would be relatively easy to try to sort IPA Monitoring data by Strategy within Measures, Milestones, etc. 

And we can also look into filtering, so that only selected strategies would be displayed in IPA MONITORING. Adding this feature may be more complicated, but we will look into it. 

For now, we can help you use the Data Download feature to accomplish this. 

Keep bringing your questions, concerns, ideas!

Best and thanks,
David

**Comment by dlounsbu** [comment]
@donriepurcell 

Let's discuss how to present this to Jeff. 
![MONITORING Milestones clip](https://user-images.githubusercontent.com/20574023/129773936-9ff1c5a6-bda1-4316-81ef-c968266c610e.JPG)

We just need to ask that, for IPA Monitoring of Milestones, the summary table rows are sored first by IPA/Strategy code, and then by (start date). 

Thoughts?

**Comment by dlounsbu** [comment]
Also, @donriepurcell , maybe we should ask Jeff to set up a GitHub account, so that we can add him to certain Issue Cards. Would that help us streamline things?

**Comment by donriepurcell** [comment]
Hi Profe

We can meet any time you like. I can working on get tracker stuff for ulster counties

From: David W Lounsbury ***@***.***>
Date: Tuesday, August 17, 2021 at 1:37 PM
To: dlounsbu/NYHEALing-IPAtracker-support ***@***.***>
Cc: Donrie Purcell ***@***.***>, Mention ***@***.***>
Subject: Re: [dlounsbu/NYHEALing-IPAtracker-support] Service Request by Anna N. Weiskopf about Milestone data sorting (#10)
CAUTION: This email comes from an external source; the attachments and/or links may compromise our secure environment. Do not open or click on suspicious emails. Please click on the “Phish Alert” button on the top right of the Outlook dashboard to report any suspicious emails.

@donriepurcell<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fdonriepurcell&data=04%7C01%7Cdonrie.purcell%40einsteinmed.org%7Ca34a5589b01c4906480008d961a5af82%7C9c01f0fd65e040c089a82dfd51e62025%7C0%7C0%7C637648186511563972%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=5hHCC01lptrVSfOJ5NyHMY1m4ImpUU7cpzl1jrXxcyY%3D&reserved=0>

Let's discuss how to present this to Jeff.
[MONITORING Milestones clip]<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F20574023%2F129773936-9ff1c5a6-bda1-4316-81ef-c968266c610e.JPG&data=04%7C01%7Cdonrie.purcell%40einsteinmed.org%7Ca34a5589b01c4906480008d961a5af82%7C9c01f0fd65e040c089a82dfd51e62025%7C0%7C0%7C637648186511573964%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=EyikqKm0EY8StmMC2v0gy1N8%2FuEn%2BuD6xEsj%2F1zj48Y%3D&reserved=0>

We just need to ask that, for IPA Monitoring of Milestones, the summary table rows are sored first by IPA/Strategy code, and then by (start date).

Thoughts?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fdlounsbu%2FNYHEALing-IPAtracker-support%2Fissues%2F10%23issuecomment-900500166&data=04%7C01%7Cdonrie.purcell%40einsteinmed.org%7Ca34a5589b01c4906480008d961a5af82%7C9c01f0fd65e040c089a82dfd51e62025%7C0%7C0%7C637648186511573964%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=MVRSV7oeWas2vPG9xCEMqWFxL33aLXCG0qc5mBviKuQ%3D&reserved=0>, or unsubscribe<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FATJKBBLOLW62XIVFZXSQQ6TT5KM5RANCNFSM5B7O2EFA&data=04%7C01%7Cdonrie.purcell%40einsteinmed.org%7Ca34a5589b01c4906480008d961a5af82%7C9c01f0fd65e040c089a82dfd51e62025%7C0%7C0%7C637648186511573964%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=dd3sLCQrOa7nwXjK7hVNdhRIEWyyFFRcFxknd%2FdbJEk%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Cdonrie.purcell%40einsteinmed.org%7Ca34a5589b01c4906480008d961a5af82%7C9c01f0fd65e040c089a82dfd51e62025%7C0%7C0%7C637648186511583957%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=1FqaGUUwMvz1M57obBjj10w7fn9Jl0XUYwQuztvN8Rs%3D&reserved=0> or Android<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26utm_campaign%3Dnotification-email&data=04%7C01%7Cdonrie.purcell%40einsteinmed.org%7Ca34a5589b01c4906480008d961a5af82%7C9c01f0fd65e040c089a82dfd51e62025%7C0%7C0%7C637648186511583957%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=76o9EmruRZ2L14oraQKyRnCQy5vZKOInAwKNfZgncgg%3D&reserved=0>.

**Comment by dlounsbu** [comment]
I am in meeting all afternoon, through 6:30pm. Sorry. 

Let's go ahead and ask Jeff to add this sorting feature in IPA Monitoring. I think that we should ask Jeff to have all summary data tables in IPA Monitoring sort by IPA/Strategy name (usually the first table column) and then by the date field.

**Comment by dlounsbu** [comment]
> I am in meeting all afternoon, through 6:30pm. Sorry.
> 
> Let's go ahead and ask Jeff to add this sorting feature in IPA Monitoring. I think that we should ask Jeff to have all summary data tables in IPA Monitoring sort by IPA/Strategy name (usually the first table column) and then by the date field.

@donriepurcell At your earliest convenience, let’s have Jeff make this enhancement. Thanks

**Comment by dlounsbu** [comment]
> @donriepurcell
> 
> Let's discuss how to present this to Jeff.
> ![MONITORING Milestones clip](https://user-images.githubusercontent.com/20574023/129773936-9ff1c5a6-bda1-4316-81ef-c968266c610e.JPG)
> 
> We just need to ask that, for IPA Monitoring of Milestones, the summary table rows are sored first by IPA/Strategy code, and then by (start date).
> 
> Thoughts?

@jbazinet1111 If you can ADD the feature to sort these history tables by IPA/Strategy name AND date? THANKS

**Comment by dlounsbu** [comment]
From: Jeff Bazinet [mailto:jbazinet@northcountryinitiative.org] 
Sent: Wednesday, August 18, 2021 12:54 PM
To: Donrie Purcell <donrie.purcell@einsteinmed.org>; david lounsbury <david.lounsbury@einsteinmed.org>
Subject: Baseline person breakdown

CAUTION: This email comes from an external source; the attachments and/or links may compromise our secure environment. Do not open or click on suspicious emails. Please click on the “Phish Alert” button on the top right of the Outlook dashboard to report any suspicious emails.

Ok, we have figured out the issue and it pertains to the rendering of the grid that shows the measures – in both Specification and Monitoring.

I’d like to propose a bit of a graphical change. We simply have too much data to display in the grids.
I’d like to change the grid into a list box, showing the measures, and clicking on one of the measures will show all the data for that measure. The add/edit/delete process will stay the same.
The drawback is that while you can see all the measures in the list, you can’t see all the additional information without clicking on one of the measures.

Let me know if this works. I think it’s probably the best bet given the screen real estate we’re dealing with, but we can force it if you want to keep it the same.





                                                                                                                                                                                                                                            
This electronic message is intended to be for the use only of the named recipient, and may contain information from the North Country Initiative that is confidential or privileged. If you are not the intended recipient, you are hereby notified that any disclosure, copying, distribution or use of the contents of this message is strictly prohibited. If you have received this message in error or are not the named recipient, please notify us immediately, either by contacting the sender at the electronic mail address noted above or by calling the North Country Initiative at (315) 755-2020 x 23, and delete and destroy all copies of this message.

**Comment by dlounsbu** [comment]
> From: Jeff Bazinet [mailto:[jbazinet@northcountryinitiative.org](mailto:jbazinet@northcountryinitiative.org)]
> Sent: Wednesday, August 18, 2021 12:54 PM
> To: Donrie Purcell [donrie.purcell@einsteinmed.org](mailto:donrie.purcell@einsteinmed.org); david lounsbury [david.lounsbury@einsteinmed.org](mailto:david.lounsbury@einsteinmed.org)
> Subject: Baseline person breakdown
> 
> CAUTION: This email comes from an external source; the attachments and/or links may compromise our secure environment. Do not open or click on suspicious emails. Please click on the “Phish Alert” button on the top right of the Outlook dashboard to report any suspicious emails.
> 
> Ok, we have figured out the issue and it pertains to the rendering of the grid that shows the measures – in both Specification and Monitoring.
> 
> I’d like to propose a bit of a graphical change. We simply have too much data to display in the grids.
> I’d like to change the grid into a list box, showing the measures, and clicking on one of the measures will show all the data for that measure. The add/edit/delete process will stay the same.
> The drawback is that while you can see all the measures in the list, you can’t see all the additional information without clicking on one of the measures.
> 
> Let me know if this works. I think it’s probably the best bet given the screen real estate we’re dealing with, but we can force it if you want to keep it the same.
> 
> This electronic message is intended to be for the use only of the named recipient, and may contain information from the North Country Initiative that is confidential or privileged. If you are not the intended recipient, you are hereby notified that any disclosure, copying, distribution or use of the contents of this message is strictly prohibited. If you have received this message in error or are not the named recipient, please notify us immediately, either by contacting the sender at the electronic mail address noted above or by calling the North Country Initiative at (315) 755-2020 x 23, and delete and destroy all copies of this message.

@jbazinet1111 I think this is a good solution. I personally do not mind the long history tables, but I think users will appreciate what you are proposing! How many hours would you like to do this work?

**Comment by dlounsbu** [comment]
@jbazinet1111 

Any need for feedback on this request? When might we be able to beta test? 

Best,
David

**Comment by dlounsbu** [comment]
@donriepurcell and @jbazinet1111 

Any updates for this feature, too? If we need to discuss, please reach out. 

Best,
DL

**Comment by jbazinet1111** [comment]
The IPA Monitoring lists are now sorted by strategy and then date.

**Comment by dlounsbu** [comment]
> The IPA Monitoring lists are now sorted by strategy and then date.

Excellent! 

@Donrie, please update Ana about this! Maybe Monika, too!

**Comment by dlounsbu** [comment]
> > The IPA Monitoring lists are now sorted by strategy and then date.
> 
> Excellent!
> 
> @DONRIE, please update Ana about this! Maybe Monika, too!

@donriepurcell if all looks good, at your convenience, you can close this issue.

**Comment by dlounsbu** [comment]
From: david lounsbury 
Sent: Wednesday, September 8, 2021 8:20 PM
To: Anna N. Weiskopf <aw3391@columbia.edu>
Cc: Donrie Purcell <donrie.purcell@einsteinmed.org>; Nicholas Bove <nicholas.bove@einsteinmed.org>; Anika Buch <ambuch@princeton.edu>; Nasim Sabounchi <Nasim.Sabounchi@sph.cuny.edu>; Emma Rodgers <emr2241@columbia.edu>
Subject: RE: Questions about IPA tracker

Hi Anna:

Milestones are now sorting by Strategy Name. 

This should improve use of this part of the Tracker. Let us know if this fix is working for you.

Best and thanks,
David
