### ISSUE TITLE
Service Request by David Lounsbury to make short demo video of Tracker MONITORING features

### ISSUE THREAD

**Issue by dlounsbu** [dlounsbu/NYHEALing-IPAtracker-support#62]
- [x] e-mail acknowledging that User's Qualtrics Service Request Form was sent
- [ ] Problem NOT RESOLVED
- [ ] Problem PARTIALLY RESOLVED 
- [ ] Problem FULLY RESOLVED and Issue is Closed
- [ ] Qualtrics Post-Service Request Survey was sent to User

Use comments feature (below) to document:

1. A clear and concise description of the solution.

2. A clear and concise description of any alternative solutions or features you've considered.

3. Any additional context, such as screenshots about the problem.
<html xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:w="urn:schemas-microsoft-com:office:word"
xmlns:m="http://schemas.microsoft.com/office/2004/12/omml"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Word.Document>
<meta name=Generator content="Microsoft Word 15">
<meta name=Originator content="Microsoft Word 15">
<link rel=File-List
href="file:///C:/Users/dlounsbu/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">

<link rel=themeData
href="file:///C:/Users/dlounsbu/AppData/Local/Temp/msohtmlclip1/01/clip_themedata.thmx">
<link rel=colorSchemeMapping
href="file:///C:/Users/dlounsbu/AppData/Local/Temp/msohtmlclip1/01/clip_colorschememapping.xml">

<style>

</style>

</head>

<body lang=EN-US link=blue vlink="#954F72" style='tab-interval:.5in'>

<p class=MsoNormal><span style='font-size:11.0pt;font-family:"Calibri",sans-serif;
mso-ascii-theme-font:minor-latin;mso-hansi-theme-font:minor-latin;mso-bidi-font-family:
"Times New Roman";mso-bidi-theme-font:minor-bidi;color:#1F497D'><o:p>&nbsp;</o:p></span></p>

<p class=MsoNormal><span style='font-size:11.0pt;font-family:"Calibri",sans-serif;
mso-ascii-theme-font:minor-latin;mso-hansi-theme-font:minor-latin;mso-bidi-font-family:
"Times New Roman";mso-bidi-theme-font:minor-bidi;color:#1F497D'><o:p>&nbsp;</o:p></span></p>

<p class=MsoNormal><a name="_MailOriginal"><b><span style='font-size:11.0pt;
font-family:"Calibri",sans-serif;mso-fareast-font-family:"Times New Roman"'>From:</span></b></a><span
style='mso-bookmark:_MailOriginal'><span style='font-size:11.0pt;font-family:
"Calibri",sans-serif;mso-fareast-font-family:"Times New Roman"'> Jessica
Neufeld [mailto:jn2434@columbia.edu] <br>
<b>Sent:</b> Tuesday, October 26, 2021 3:34 PM<br>
<b>To:</b> david lounsbury &lt;david.lounsbury@einsteinmed.org&gt;<br>
<b>Cc:</b> Emma Rodgers &lt;emr2241@columbia.edu&gt;; Sandra Rodriguez
&lt;sr3717@columbia.edu&gt;; Donrie Purcell &lt;donrie.purcell@einsteinmed.org&gt;;
Nicholas Bove &lt;nicholas.bove@einsteinmed.org&gt;; Timothy Hunt
&lt;th2258@columbia.edu&gt;<br>
<b>Subject:</b> Re: Touch base / collaborate<o:p></o:p></span></span></p>

<p class=MsoNormal><span style='mso-bookmark:_MailOriginal'><o:p>&nbsp;</o:p></span></p>

CAUTION: This email comes from an external   source; the attachments and/or links may compromise our secure environment.   Do not open or click on suspicious emails. Please click on the “Phish Alert”   button on the top right of the Outlook dashboard to report any suspicious   emails.
--

<p class=MsoNormal style='mso-margin-top-alt:auto;mso-margin-bottom-alt:auto'><span
style='mso-bookmark:_MailOriginal'>Hi David,&nbsp; <o:p></o:p></span></p>

<p class=MsoNormal style='mso-margin-top-alt:auto;mso-margin-bottom-alt:auto'><span
style='mso-bookmark:_MailOriginal'>&nbsp;<o:p></o:p></span></p>

<p class=MsoNormal style='mso-margin-top-alt:auto;mso-margin-bottom-alt:auto'><span
style='mso-bookmark:_MailOriginal'>Sure, are you and Donrie available this
Wednesday at 4pm?&nbsp;<o:p></o:p></span></p>

<p class=MsoNormal style='mso-margin-top-alt:auto;mso-margin-bottom-alt:auto'><span
style='mso-bookmark:_MailOriginal'>&nbsp;<o:p></o:p></span></p>

<p class=MsoNormal style='mso-margin-top-alt:auto;mso-margin-bottom-alt:auto'><span
style='mso-bookmark:_MailOriginal'>Best,<br>
Jessica<o:p></o:p></span></p>

<p class=MsoNormal style='mso-margin-top-alt:auto;mso-margin-bottom-alt:auto'><span
style='mso-bookmark:_MailOriginal'>&nbsp;<o:p></o:p></span></p>

<p class=MsoNormal style='mso-margin-top-alt:auto;mso-margin-bottom-alt:auto'><span
style='mso-bookmark:_MailOriginal'>On Mon, Oct 18, 2021 at 4:58 PM david
lounsbury &lt;</span><a href="mailto:david.lounsbury@einsteinmed.org"
target="_blank"><span style='mso-bookmark:_MailOriginal'>david.lounsbury@einsteinmed.org</span><span
style='mso-bookmark:_MailOriginal'></span></a><span style='mso-bookmark:_MailOriginal'>&gt;
wrote:<o:p></o:p></span></p>

<p class=MsoNormal style='mso-margin-top-alt:auto;mso-margin-bottom-alt:auto'><span
style='mso-bookmark:_MailOriginal'>Hi Jessica: <o:p></o:p></span></p>

<p class=MsoNormal style='mso-margin-top-alt:auto;mso-margin-bottom-alt:auto'><span
style='mso-bookmark:_MailOriginal'>&nbsp;<o:p></o:p></span></p>

<p class=MsoNormal style='mso-margin-top-alt:auto;mso-margin-bottom-alt:auto'><span
style='mso-bookmark:_MailOriginal'>I am feeling anxious about not having
provided more feedback to the county PMs and DCs re: visualizations about how
their IPAs/Smart Strategies are working. <o:p></o:p></span></p>

<p class=MsoNormal style='mso-margin-top-alt:auto;mso-margin-bottom-alt:auto'><span
style='mso-bookmark:_MailOriginal'>&nbsp;<o:p></o:p></span></p>

<p class=MsoNormal style='mso-margin-top-alt:auto;mso-margin-bottom-alt:auto'><span
style='mso-bookmark:_MailOriginal'>I feel like Donrie and I have been moving
too slowly. <o:p></o:p></span></p>

<p class=MsoNormal style='mso-margin-top-alt:auto;mso-margin-bottom-alt:auto'><span
style='mso-bookmark:_MailOriginal'>&nbsp;<o:p></o:p></span></p>

<p class=MsoNormal style='mso-margin-top-alt:auto;mso-margin-bottom-alt:auto'><span
style='mso-bookmark:_MailOriginal'>I know you are working on this, too. We need
to find ways to share useful information quickly. Your perspective would be helpful.
<o:p></o:p></span></p>

<p class=MsoNormal style='mso-margin-top-alt:auto;mso-margin-bottom-alt:auto'><span
style='mso-bookmark:_MailOriginal'>&nbsp;<o:p></o:p></span></p>

<p class=MsoNormal style='mso-margin-top-alt:auto;mso-margin-bottom-alt:auto'><span
style='mso-bookmark:_MailOriginal'>Do you want to touch base about this later
this week, maybe Wed or Thursday? <o:p></o:p></span></p>

<p class=MsoNormal style='mso-margin-top-alt:auto;mso-margin-bottom-alt:auto'><span
style='mso-bookmark:_MailOriginal'>&nbsp;<o:p></o:p></span></p>

<p class=MsoNormal style='mso-margin-top-alt:auto;mso-margin-bottom-alt:auto'><span
style='mso-bookmark:_MailOriginal'>DL<o:p></o:p></span></p>

<p class=MsoNormal style='mso-margin-top-alt:auto;mso-margin-bottom-alt:auto'><span
style='mso-bookmark:_MailOriginal'>&nbsp;<o:p></o:p></span></p>

<p class=MsoNormal style='mso-margin-top-alt:auto;mso-margin-bottom-alt:auto'><span
style='mso-bookmark:_MailOriginal'>&nbsp;<o:p></o:p></span></p>

<p class=MsoNormal style='mso-margin-top-alt:auto;mso-margin-bottom-alt:auto'><span
style='mso-bookmark:_MailOriginal'><br clear=all style='mso-special-character:
line-break'>
<o:p></o:p></span></p>

<p class=MsoNormal style='mso-margin-top-alt:auto;mso-margin-bottom-alt:auto'><span
style='mso-bookmark:_MailOriginal'>&nbsp;<o:p></o:p></span></p>

<p class=MsoNormal style='mso-margin-top-alt:auto;mso-margin-bottom-alt:auto'><span
style='mso-bookmark:_MailOriginal'>-- <o:p></o:p></span></p>

<p class=MsoNormal style='mso-margin-top-alt:auto;mso-margin-bottom-alt:auto'><span
style='mso-bookmark:_MailOriginal'>&nbsp;<o:p></o:p></span></p>

<p class=MsoNormal style='mso-margin-top-alt:auto;mso-margin-bottom-alt:auto'><span
style='mso-bookmark:_MailOriginal'><b><span style='font-family:"Arial",sans-serif;
color:black'>Jessica Neufeld, MPH</span></b><o:p></o:p></span></p>

<p class=MsoNormal style='mso-margin-top-alt:auto;mso-margin-bottom-alt:auto'><span
style='mso-bookmark:_MailOriginal'><span style='font-family:"Arial",sans-serif;
color:black'>Program Manager&nbsp;</span><o:p></o:p></span></p>

<p class=MsoNormal style='mso-margin-top-alt:auto;mso-margin-bottom-alt:auto'><span
style='mso-bookmark:_MailOriginal'><span style='font-family:"Arial",sans-serif;
color:black'>HEALing Communities Study</span><o:p></o:p></span></p>

<p class=MsoNormal style='mso-margin-top-alt:auto;mso-margin-bottom-alt:auto'><span
style='mso-bookmark:_MailOriginal'><span style='font-family:"Arial",sans-serif;
color:black'>Social Intervention Group</span><o:p></o:p></span></p>

<p class=MsoNormal style='mso-margin-top-alt:auto;mso-margin-bottom-alt:auto'><span
style='mso-bookmark:_MailOriginal'><span style='font-family:"Arial",sans-serif;
color:black'>Columbia University School of Social Work<br>
1255 Amsterdam Avenue</span><o:p></o:p></span></p>

<p class=MsoNormal style='mso-margin-top-alt:auto;mso-margin-bottom-alt:auto'><span
style='mso-bookmark:_MailOriginal'><span style='font-family:"Arial",sans-serif;
color:black'>New York, NY 10027</span><o:p></o:p></span></p>

<p class=MsoNormal style='mso-margin-top-alt:auto;mso-margin-bottom-alt:auto'><span
style='mso-bookmark:_MailOriginal'></span><a href="mailto:jn2434@columbia.edu"
target="_blank"><span style='mso-bookmark:_MailOriginal'>jn2434@columbia.edu</span><span
style='mso-bookmark:_MailOriginal'></span></a><span style='mso-bookmark:_MailOriginal'>&nbsp;&nbsp;<o:p></o:p></span></p>

<p class=MsoNormal style='mso-margin-top-alt:auto;mso-margin-bottom-alt:auto'><span
style='mso-bookmark:_MailOriginal'><span style='font-family:"Arial",sans-serif;
color:#222222'>Website:&nbsp;</span></span><span style='mso-bookmark:_MailOriginal'><span
style='font-family:"Arial",sans-serif'>&nbsp;</span></span><a
href="https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fsig.columbia.edu%2F&amp;data=04%7C01%7Cdavid.lounsbury%40einsteinmed.org%7C2dc696c69337402c0ac508d998b7a47f%7C9c01f0fd65e040c089a82dfd51e62025%7C0%7C0%7C637708736800723503%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&amp;sdata=wS0ZczIDUdOjmnfe1VCat3eI310vWMst20H5JTCViJ0%3D&amp;reserved=0"
target="_blank" originalsrc="https://sig.columbia.edu/"
shash="N7lu4HJr8XtlX7ULyvpq18rEKlnTnO6AuDwDgYOcDc3M3ED9N5A+DtP4GehXZ/aXACKSp95QjtWa1InayiL+2hpE5HYb12Uyh/rTdFP9j1/2YhJD/47f3JLw70LEbeq+tOE6ZB4JYCQ5bbzux0go9KEDc+d786jG6lVbOrUkgO0="><span
style='mso-bookmark:_MailOriginal'><span style='font-family:"Arial",sans-serif;
color:#1155CC'>https://sig.columbia.edu/</span></span><span style='mso-bookmark:
_MailOriginal'></span></a><span style='mso-bookmark:_MailOriginal'><o:p></o:p></span></p>

<p class=MsoNormal style='mso-margin-top-alt:auto;mso-margin-bottom-alt:auto'><span
style='mso-bookmark:_MailOriginal'>&nbsp;<o:p></o:p></span></p>

<p class=MsoNormal style='mso-margin-top-alt:auto;mso-margin-bottom-alt:auto'><span
style='mso-bookmark:_MailOriginal'><span style='font-family:"Arial",sans-serif;
color:#222222'>&nbsp; &nbsp;</span><o:p></o:p></span></p>

<p class=MsoNormal style='mso-margin-top-alt:auto;mso-margin-bottom-alt:auto'><span
style='mso-bookmark:_MailOriginal'><br clear=all style='mso-special-character:
line-break'>
<o:p></o:p></span></p>

<p class=MsoNormal style='mso-margin-top-alt:auto;mso-margin-bottom-alt:auto'><span
style='mso-bookmark:_MailOriginal'>&nbsp;<o:p></o:p></span></p>

<p class=MsoNormal style='mso-margin-top-alt:auto;mso-margin-bottom-alt:auto'><span
style='mso-bookmark:_MailOriginal'>-- <o:p></o:p></span></p>

<p class=MsoNormal style='mso-margin-top-alt:auto;mso-margin-bottom-alt:auto'><span
style='mso-bookmark:_MailOriginal'>&nbsp;<o:p></o:p></span></p>

<p class=MsoNormal style='mso-margin-top-alt:auto;mso-margin-bottom-alt:auto'><span
style='mso-bookmark:_MailOriginal'><b><span style='font-family:"Arial",sans-serif;
color:black'>Jessica Neufeld, MPH</span></b><o:p></o:p></span></p>

<p class=MsoNormal style='mso-margin-top-alt:auto;mso-margin-bottom-alt:auto'><span
style='mso-bookmark:_MailOriginal'><span style='font-family:"Arial",sans-serif;
color:black'>Program Manager&nbsp;</span><o:p></o:p></span></p>

<p class=MsoNormal style='mso-margin-top-alt:auto;mso-margin-bottom-alt:auto'><span
style='mso-bookmark:_MailOriginal'><span style='font-family:"Arial",sans-serif;
color:black'>HEALing Communities Study</span><o:p></o:p></span></p>

<p class=MsoNormal style='mso-margin-top-alt:auto;mso-margin-bottom-alt:auto'><span
style='mso-bookmark:_MailOriginal'><span style='font-family:"Arial",sans-serif;
color:black'>Social Intervention Group</span><o:p></o:p></span></p>

<p class=MsoNormal style='mso-margin-top-alt:auto;mso-margin-bottom-alt:auto'><span
style='mso-bookmark:_MailOriginal'><span style='font-family:"Arial",sans-serif;
color:black'>Columbia University School of Social Work<br>
1255 Amsterdam Avenue</span><o:p></o:p></span></p>

<p class=MsoNormal style='mso-margin-top-alt:auto;mso-margin-bottom-alt:auto'><span
style='mso-bookmark:_MailOriginal'><span style='font-family:"Arial",sans-serif;
color:black'>New York, NY 10027</span><o:p></o:p></span></p>

<p class=MsoNormal style='mso-margin-top-alt:auto;mso-margin-bottom-alt:auto'><span
style='mso-bookmark:_MailOriginal'></span><a href="mailto:jn2434@columbia.edu"
target="_blank"><span style='mso-bookmark:_MailOriginal'>jn2434@columbia.edu</span><span
style='mso-bookmark:_MailOriginal'></span></a><span style='mso-bookmark:_MailOriginal'>&nbsp;&nbsp;<o:p></o:p></span></p>

<p class=MsoNormal style='mso-margin-top-alt:auto;mso-margin-bottom-alt:auto'><span
style='mso-bookmark:_MailOriginal'><span style='font-family:"Arial",sans-serif;
color:#222222'>Website:&nbsp;</span></span><span style='mso-bookmark:_MailOriginal'><span
style='font-family:"Arial",sans-serif'>&nbsp;</span></span><a
href="https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fsig.columbia.edu%2F&amp;data=04%7C01%7Cdavid.lounsbury%40einsteinmed.org%7C2dc696c69337402c0ac508d998b7a47f%7C9c01f0fd65e040c089a82dfd51e62025%7C0%7C0%7C637708736800723503%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&amp;sdata=wS0ZczIDUdOjmnfe1VCat3eI310vWMst20H5JTCViJ0%3D&amp;reserved=0"
target="_blank" originalsrc="https://sig.columbia.edu/"
shash="N7lu4HJr8XtlX7ULyvpq18rEKlnTnO6AuDwDgYOcDc3M3ED9N5A+DtP4GehXZ/aXACKSp95QjtWa1InayiL+2hpE5HYb12Uyh/rTdFP9j1/2YhJD/47f3JLw70LEbeq+tOE6ZB4JYCQ5bbzux0go9KEDc+d786jG6lVbOrUkgO0="><span
style='mso-bookmark:_MailOriginal'><span style='font-family:"Arial",sans-serif;
color:#1155CC'>https://sig.columbia.edu/</span></span><span style='mso-bookmark:
_MailOriginal'></span></a><span style='mso-bookmark:_MailOriginal'><o:p></o:p></span></p>

<p class=MsoNormal style='mso-margin-top-alt:auto;mso-margin-bottom-alt:auto'><span
style='mso-bookmark:_MailOriginal'>&nbsp;<o:p></o:p></span></p>

<p class=MsoNormal style='mso-margin-top-alt:auto;mso-margin-bottom-alt:auto'><span
style='mso-bookmark:_MailOriginal'><span style='font-family:"Arial",sans-serif;
color:#222222'>&nbsp; &nbsp;</span><o:p></o:p></span></p>

<p class=MsoNormal style='mso-margin-top-alt:auto;mso-margin-bottom-alt:auto'><span
style='mso-bookmark:_MailOriginal'><br clear=all style='mso-special-character:
line-break'>
<o:p></o:p></span></p>

<p class=MsoNormal style='mso-margin-top-alt:auto;mso-margin-bottom-alt:auto'><span
style='mso-bookmark:_MailOriginal'>&nbsp;<o:p></o:p></span></p>

<p class=MsoNormal style='mso-margin-top-alt:auto;mso-margin-bottom-alt:auto'><span
style='mso-bookmark:_MailOriginal'>-- <o:p></o:p></span></p>

<p class=MsoNormal style='mso-margin-top-alt:auto;mso-margin-bottom-alt:auto'><span
style='mso-bookmark:_MailOriginal'>&nbsp;<o:p></o:p></span></p>

<p class=MsoNormal style='mso-margin-top-alt:auto;mso-margin-bottom-alt:auto'><span
style='mso-bookmark:_MailOriginal'><b><span style='font-family:"Arial",sans-serif;
color:black'>Jessica Neufeld, MPH</span></b><o:p></o:p></span></p>

<p class=MsoNormal style='mso-margin-top-alt:auto;mso-margin-bottom-alt:auto'><span
style='mso-bookmark:_MailOriginal'><span style='font-family:"Arial",sans-serif;
color:black'>Program Manager&nbsp;</span><o:p></o:p></span></p>

<p class=MsoNormal style='mso-margin-top-alt:auto;mso-margin-bottom-alt:auto'><span
style='mso-bookmark:_MailOriginal'><span style='font-family:"Arial",sans-serif;
color:black'>HEALing Communities Study</span><o:p></o:p></span></p>

<p class=MsoNormal style='mso-margin-top-alt:auto;mso-margin-bottom-alt:auto'><span
style='mso-bookmark:_MailOriginal'><span style='font-family:"Arial",sans-serif;
color:black'>Social Intervention Group</span><o:p></o:p></span></p>

<p class=MsoNormal style='mso-margin-top-alt:auto;mso-margin-bottom-alt:auto'><span
style='mso-bookmark:_MailOriginal'><span style='font-family:"Arial",sans-serif;
color:black'>Columbia University School of Social Work<br>
1255 Amsterdam Avenue</span><o:p></o:p></span></p>

<p class=MsoNormal style='mso-margin-top-alt:auto;mso-margin-bottom-alt:auto'><span
style='mso-bookmark:_MailOriginal'><span style='font-family:"Arial",sans-serif;
color:black'>New York, NY 10027</span><o:p></o:p></span></p>

<p class=MsoNormal style='mso-margin-top-alt:auto;mso-margin-bottom-alt:auto'><span
style='mso-bookmark:_MailOriginal'></span><a href="mailto:jn2434@columbia.edu"
target="_blank"><span style='mso-bookmark:_MailOriginal'>jn2434@columbia.edu</span><span
style='mso-bookmark:_MailOriginal'></span></a><span style='mso-bookmark:_MailOriginal'>&nbsp;&nbsp;<o:p></o:p></span></p>

<p class=MsoNormal style='mso-margin-top-alt:auto;mso-margin-bottom-alt:auto'><span
style='mso-bookmark:_MailOriginal'><span style='font-family:"Arial",sans-serif;
color:#222222'>Website:&nbsp;</span></span><span style='mso-bookmark:_MailOriginal'><span
style='font-family:"Arial",sans-serif'>&nbsp;</span></span><a
href="https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fsig.columbia.edu%2F&amp;data=04%7C01%7Cdavid.lounsbury%40einsteinmed.org%7C2dc696c69337402c0ac508d998b7a47f%7C9c01f0fd65e040c089a82dfd51e62025%7C0%7C0%7C637708736800733459%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&amp;sdata=cVHs69pwcC6qSS03Ahw4dOO9SzMenmAt%2BbYNirrnz0s%3D&amp;reserved=0"
target="_blank" originalsrc="https://sig.columbia.edu/"
shash="YHT18GkWBlrcDzxKtv6r0v5cTKv6ISRT6GeFOpH9QYKqslJG1Rb5xgVjeALSzTBaYyZic/AU9tzW5tM15DpBgA6/EIdUOnBCtaadivVYTC33CDP4olkfwlkTZ5H1b0m/nBlAGB6JTAl6zMm/U+EHyEh1InxzRXe1D9YYNCjpcgw="><span
style='mso-bookmark:_MailOriginal'><span style='font-family:"Arial",sans-serif;
color:#1155CC'>https://sig.columbia.edu/</span></span><span style='mso-bookmark:
_MailOriginal'></span></a><span style='mso-bookmark:_MailOriginal'><o:p></o:p></span></p>

<p class=MsoNormal style='mso-margin-top-alt:auto;mso-margin-bottom-alt:auto'><span
style='mso-bookmark:_MailOriginal'>&nbsp;<o:p></o:p></span></p>

<p class=MsoNormal style='mso-margin-top-alt:auto;mso-margin-bottom-alt:auto'><span
style='mso-bookmark:_MailOriginal'><span style='font-family:"Arial",sans-serif;
color:#222222'>&nbsp; &nbsp;</span><o:p></o:p></span></p>

<p class=MsoNormal style='mso-margin-top-alt:auto;mso-margin-bottom-alt:auto'><span
style='mso-bookmark:_MailOriginal'><br clear=all>
<br>
-- <o:p></o:p></span></p>

<p class=MsoNormal style='mso-margin-top-alt:auto;mso-margin-bottom-alt:auto'><span
style='mso-bookmark:_MailOriginal'><b>Emma Rodgers, MS</b><br>
Director of Community Engagement<br>
HEALing Communities Study<br>
Social Intervention Group<br>
Columbia University School of Social Work<br>
</span><a href="mailto:jld2023@columbia.edu" target="_blank"><span
style='mso-bookmark:_MailOriginal'>emr2241@columbia.edu</span><span
style='mso-bookmark:_MailOriginal'></span></a><span style='mso-bookmark:_MailOriginal'><o:p></o:p></span></p>

<p class=MsoNormal style='mso-margin-top-alt:auto;mso-margin-bottom-alt:auto'><span
style='mso-bookmark:_MailOriginal'>Phone: (212) 853-7273<o:p></o:p></span></p>

<p class=MsoNormal style='mso-margin-top-alt:auto;mso-margin-bottom-alt:auto'><span
style='mso-bookmark:_MailOriginal'></span><a
href="https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fsig.columbia.edu%2F&amp;data=04%7C01%7Cdavid.lounsbury%40einsteinmed.org%7C2dc696c69337402c0ac508d998b7a47f%7C9c01f0fd65e040c089a82dfd51e62025%7C0%7C0%7C637708736800733459%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&amp;sdata=cVHs69pwcC6qSS03Ahw4dOO9SzMenmAt%2BbYNirrnz0s%3D&amp;reserved=0"
target="_blank" originalsrc="https://sig.columbia.edu/"
shash="YHT18GkWBlrcDzxKtv6r0v5cTKv6ISRT6GeFOpH9QYKqslJG1Rb5xgVjeALSzTBaYyZic/AU9tzW5tM15DpBgA6/EIdUOnBCtaadivVYTC33CDP4olkfwlkTZ5H1b0m/nBlAGB6JTAl6zMm/U+EHyEh1InxzRXe1D9YYNCjpcgw="><span
style='mso-bookmark:_MailOriginal'>https://sig.columbia.edu/</span><span
style='mso-bookmark:_MailOriginal'></span></a><span style='mso-bookmark:_MailOriginal'><o:p></o:p></span></p>

<p class=MsoNormal style='mso-margin-top-alt:auto;mso-margin-bottom-alt:auto'><span
style='mso-bookmark:_MailOriginal'>&nbsp;<o:p></o:p></span></p>

<p class=MsoNormal style='mso-margin-top-alt:auto;mso-margin-bottom-alt:auto'><span
style='mso-bookmark:_MailOriginal'><b><i><span style='font-size:10.0pt;
font-family:"Arial",sans-serif'>We at CSSW condemn anti-Black racism in all its
forms and are committed not just to making statements, but to taking action. </span></i></b><o:p></o:p></span></p>

<p class=MsoNormal><span style='mso-bookmark:_MailOriginal'><span
style='mso-fareast-font-family:"Times New Roman"'><br clear=all
style='mso-special-character:line-break'>
<o:p></o:p></span></span></p>

<p class=MsoNormal><span style='mso-bookmark:_MailOriginal'><span
style='mso-fareast-font-family:"Times New Roman"'><o:p>&nbsp;</o:p></span></span></p>

<p class=MsoNormal><span style='mso-bookmark:_MailOriginal'><span
style='mso-fareast-font-family:"Times New Roman"'>-- <o:p></o:p></span></span></p>

<p class=MsoNormal><span style='mso-bookmark:_MailOriginal'><span
style='mso-fareast-font-family:"Times New Roman"'><o:p>&nbsp;</o:p></span></span></p>

<p class=MsoNormal><span style='mso-bookmark:_MailOriginal'><b><span
style='font-family:"Arial",sans-serif;mso-fareast-font-family:"Times New Roman";
color:black'>Jessica Neufeld, MPH</span></b></span><span style='mso-bookmark:
_MailOriginal'><span style='mso-fareast-font-family:"Times New Roman"'><o:p></o:p></span></span></p>

<p class=MsoNormal><span style='mso-bookmark:_MailOriginal'><span
style='font-family:"Arial",sans-serif;mso-fareast-font-family:"Times New Roman";
color:black'>Program Manager&nbsp;</span></span><span style='mso-bookmark:_MailOriginal'><span
style='mso-fareast-font-family:"Times New Roman"'><o:p></o:p></span></span></p>

<p class=MsoNormal><span style='mso-bookmark:_MailOriginal'><span
style='font-family:"Arial",sans-serif;mso-fareast-font-family:"Times New Roman";
color:black'>HEALing Communities Study</span></span><span style='mso-bookmark:
_MailOriginal'><span style='mso-fareast-font-family:"Times New Roman"'><o:p></o:p></span></span></p>

<p class=MsoNormal><span style='mso-bookmark:_MailOriginal'><span
style='font-family:"Arial",sans-serif;mso-fareast-font-family:"Times New Roman";
color:black'>Social Intervention Group</span></span><span style='mso-bookmark:
_MailOriginal'><span style='mso-fareast-font-family:"Times New Roman"'><o:p></o:p></span></span></p>

<p class=MsoNormal><span style='mso-bookmark:_MailOriginal'><span
style='font-family:"Arial",sans-serif;mso-fareast-font-family:"Times New Roman";
color:black'><span style='font-stretch:normal'>Columbia University School of
Social Work</span><br style='font-stretch:normal;overflow:visible'>
<span style='font-stretch:normal'>1255 Amsterdam Avenue</span></span></span><span
style='mso-bookmark:_MailOriginal'><span style='mso-fareast-font-family:"Times New Roman"'><o:p></o:p></span></span></p>

<p class=MsoNormal><span style='mso-bookmark:_MailOriginal'><span
style='font-family:"Arial",sans-serif;mso-fareast-font-family:"Times New Roman";
color:black'>New York, NY 10027</span></span><span style='mso-bookmark:_MailOriginal'><span
style='mso-fareast-font-family:"Times New Roman"'><o:p></o:p></span></span></p>

<p class=MsoNormal><span style='mso-bookmark:_MailOriginal'></span><a
href="mailto:jn2434@columbia.edu" target="_blank"><span style='mso-bookmark:
_MailOriginal'><span style='mso-fareast-font-family:"Times New Roman"'>jn2434@columbia.edu</span></span><span
style='mso-bookmark:_MailOriginal'></span></a><span style='mso-bookmark:_MailOriginal'><span
style='mso-fareast-font-family:"Times New Roman"'>&nbsp;&nbsp;<o:p></o:p></span></span></p>

<p class=MsoNormal><span style='mso-bookmark:_MailOriginal'><span
style='font-family:"Arial",sans-serif;mso-fareast-font-family:"Times New Roman";
color:#222222'>Website:&nbsp;</span></span><span style='mso-bookmark:_MailOriginal'><span
style='font-family:"Arial",sans-serif;mso-fareast-font-family:"Times New Roman"'>&nbsp;</span></span><span
style='mso-bookmark:_MailOriginal'></span><a
href="https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fsig.columbia.edu%2F&amp;data=04%7C01%7Cdavid.lounsbury%40einsteinmed.org%7C2dc696c69337402c0ac508d998b7a47f%7C9c01f0fd65e040c089a82dfd51e62025%7C0%7C0%7C637708736800743414%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&amp;sdata=6S%2B%2FWA9bzNnzYsyIm6gbCufPlUe2eWT%2BdnW3QmWpbYY%3D&amp;reserved=0"
target="_blank" originalsrc="https://sig.columbia.edu/"
shash="lB7Ey8HV4Qu3g3yqoF7VmVtAqFwvrYZgyjq9mU9QkHf0MU60gQTh6Fhj/ft+NaX5KA9BHUJ7Wpq1wYYGhZMO7Gm74QXP7EnxpmpBhHFehUrMCrd0xdEki576P7c+YGigEkX4XsTk3LOcz7PZhu1LXQNNnAw0ug7HQkQc+igQDE8="><span
style='mso-bookmark:_MailOriginal'><span style='font-family:"Arial",sans-serif;
mso-fareast-font-family:"Times New Roman";color:#1155CC'>https://sig.columbia.edu/</span></span><span
style='mso-bookmark:_MailOriginal'></span></a><span style='mso-bookmark:_MailOriginal'><span
style='mso-fareast-font-family:"Times New Roman"'><o:p></o:p></span></span></p>

<p class=MsoNormal><span style='mso-bookmark:_MailOriginal'><span
style='mso-fareast-font-family:"Times New Roman"'><o:p>&nbsp;</o:p></span></span></p>

<p class=MsoNormal><span style='mso-bookmark:_MailOriginal'><span
style='font-family:"Arial",sans-serif;mso-fareast-font-family:"Times New Roman";
color:#222222'>&nbsp; &nbsp;</span></span><span style='mso-bookmark:_MailOriginal'></span><span
style='mso-fareast-font-family:"Times New Roman"'><o:p></o:p></span></p>

</body>

</html>
