### ISSUE TITLE
Service Request by [Putnam County team(Jessica & Katy)] to edit date created on IPA (D1) in the tracker

### ISSUE THREAD

**Issue by donriepurcell** [dlounsbu/NYHEALing-IPAtracker-support#76]
- [x] Qualtrics Service Request Form was received from User
- [x] e-mail acknowledging that User's Qualtrics Service Request Form was sent
- [ ] Problem NOT RESOLVED
- [ ] Problem PARTIALLY RESOLVED 
- [x] Problem FULLY RESOLVED and Issue is Closed
- [ ] Qualtrics Post-Service Request Survey was sent to User

Use comments feature (below) to document:

1. A clear and concise description of the solution.

2. A clear and concise description of any alternative solutions or features you've considered.

3. Any additional context, such as screenshots about the problem.

**Comment by donriepurcell** [comment]
Hi Jeff 
I am kindly ask your help to review a case (D1) on behalf of Putnam county to see if we can we the date the strategy was created edited in the system from end.

Historical perspective:

Last week Putnam county team along with Jessica asked me to copy strategy D1 from OEND and move it to MOUD. When I did that it came over to MOUD as a new strategy in MOUD with a new Date Created  12/15/2021.

They have since asked if we can make a change to reflect the correct date created on their behalf. I am unable to edit the date created on my end. Would you be kind enough to help us out with this if possible.

I have attached screen shot #1  of what it looks like in the system as it stands and screen shot #2 of previously downloaded data of its correct history for your review.
<img width="1188" alt="Screen Shot #1" src="https://user-images.githubusercontent.com/80912517/146801933-51bd2e89-c52a-47df-b845-58e18b3ff39f.png">


<img width="1274" alt="Screen Shot #2" src="https://user-images.githubusercontent.com/80912517/146801956-9267a9e0-26cf-414f-9e33-4b27391e83fe.png">

**Comment by donriepurcell** [comment]
From: Donrie Purcell <donrie.purcell@einsteinmed.edu>
Date: Thursday, January 13, 2022 at 3:04 PM
To: Jeff Bazinet <jbazinet@northcountryinitiative.org>
Cc: Nicholas Bove <nicholas.bove@einsteinmed.edu>, David Lounsbury <david.lounsbury@einsteinmed.edu>
Subject: Putnam County MOUD Strategy D1
Hi Jeff
 
I am sending a gentle reminder to ask if you can kindly change the date created to 7/26/2021 for the PUTNAM county MOUD strategy D1.
 
Please see screen shot below: 
 
 
![Screen Shot 2022-01-13 at 2 35 05 PM](https://user-images.githubusercontent.com/80912517/149401277-466561a6-fc72-4e18-8626-aeffb2111a06.png)

Regards
Donrie Purcell, PhD, MPH
 
Every generation has the obligation to free men's minds for a look at new worlds,....to look out from a higher plateau than the last generation.
Ellison S. Onizuka 


CONFIDENTIALITY: This email (including any attachments) may contain confidential, proprietary and/or privileged information. Any duplication, copying, distribution, dissemination, transmission, disclosure or use in any manner of this email (including any attachments) without the authorization of the sender is strictly prohibited. If you receive this email (including any attachments) in error, please notify the sender and delete this email (including any attachments) from your system. Thank you.

**Comment by jbazinet1111** [comment]
All set
