### ISSUE TITLE
Service Request by [Jessica ] on editing in for Green County in the IPA tracker 

### ISSUE THREAD

**Issue by donriepurcell** [dlounsbu/NYHEALing-IPAtracker-support#81]
- [x] Qualtrics Service Request Form was received from User
- [x] e-mail acknowledging that User's Qualtrics Service Request Form was sent
- [x] Problem NOT RESOLVED
- [ ] Problem PARTIALLY RESOLVED 
- [ ] Problem FULLY RESOLVED and Issue is Closed
- [ ] Qualtrics Post-Service Request Survey was sent to User

Use comments feature (below) to document:

1. A clear and concise description of the solution.

2. A clear and concise description of any alternative solutions or features you've considered.

3. Any additional context, such as screenshots about the problem.

**Comment by donriepurcell** [comment]
From: Jessica Neufeld <jn2434@columbia.edu>
Date: Tuesday, January 11, 2022 at 12:18 PM
To: Donrie Purcell <donrie.purcell@einsteinmed.edu>, David Lounsbury <david.lounsbury@einsteinmed.edu>
Subject: IPA Tracker issue - Editing Measures
CAUTION: This email comes from an external source; the attachments and/or links may compromise our secure environment. Do not open or click on suspicious emails. Please click on the “Phish Alert” button on the top right of the Outlook dashboard to report any suspicious emails.
Hi Donrie and David,  

I submitted an issue I'm having via the tracker Support site. This was related to editing the measures for data collection in Greene's IPAs. Do you know when this might be addressed? There is no immediate urgency, but I would like to anticipate the timeline. 

Thanks,
Jessica 

-- 

Jessica Neufeld, MPH
Program Manager 
HEALing Communities Study
Social Intervention Group
Columbia University School of Social Work
1255 Amsterdam Avenue
New York, NY 10027
jn2434@columbia.edu  
Website:  https://sig.columbia.edu/

**Comment by donriepurcell** [comment]
Hi Jeff 
Please see the error code below:
![Screen Shot 2022-01-11 at 2 32 49 PM](https://user-images.githubusercontent.com/80912517/149009992-4eb68c28-913b-4ff7-85e7-27f02b56c66c.png)
![Screen Shot 2022-01-11 at 2 33 47 PM](https://user-images.githubusercontent.com/80912517/149010020-16dde229-feaf-48be-a11d-64657e36b421.png)

**Comment by dlounsbu** [comment]
Hi Jeff:

DP and I see are each replicating this issue. Seems to be just for Greene County. 

Can you address ASAP??

Best,
DL

**Comment by dlounsbu** [comment]
<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:w="urn:schemas-microsoft-com:office:word"
xmlns:m="http://schemas.microsoft.com/office/2004/12/omml"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Word.Document>
<meta name=Generator content="Microsoft Word 15">
<meta name=Originator content="Microsoft Word 15">
<link rel=File-List
href="file:///C:/Users/dlounsbu/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<link rel=Edit-Time-Data
href="file:///C:/Users/dlounsbu/AppData/Local/Temp/msohtmlclip1/01/clip_editdata.mso">

<link rel=themeData
href="file:///C:/Users/dlounsbu/AppData/Local/Temp/msohtmlclip1/01/clip_themedata.thmx">
<link rel=colorSchemeMapping
href="file:///C:/Users/dlounsbu/AppData/Local/Temp/msohtmlclip1/01/clip_colorschememapping.xml">

<style>

</style>

</head>

<body lang=EN-US link="#0563C1" vlink="#954F72" style='tab-interval:.5in'>


<p class=MsoNormal><span style='font-size:11.0pt;font-family:"Calibri",sans-serif;
mso-ascii-theme-font:minor-latin;mso-hansi-theme-font:minor-latin;mso-bidi-font-family:
"Times New Roman";mso-bidi-theme-font:minor-bidi;color:#1F497D'><o:p>&nbsp;</o:p></span></p>

<p class=MsoNormal><span style='font-size:11.0pt;font-family:"Calibri",sans-serif;
mso-ascii-theme-font:minor-latin;mso-hansi-theme-font:minor-latin;mso-bidi-font-family:
"Times New Roman";mso-bidi-theme-font:minor-bidi;color:#1F497D'><o:p>&nbsp;</o:p></span></p>

<p class=MsoNormal><b><span style='font-size:11.0pt;font-family:"Calibri",sans-serif;
mso-fareast-font-family:"Times New Roman"'>From:</span></b><span
style='font-size:11.0pt;font-family:"Calibri",sans-serif;mso-fareast-font-family:
"Times New Roman"'> Jeff Bazinet [mailto:jbazinet@northcountryinitiative.org] <br>
<b>Sent:</b> Wednesday, January 12, 2022 3:31 PM<br>
<b>To:</b> Donrie Purcell &lt;donrie.purcell@einsteinmed.edu&gt;<br>
<b>Cc:</b> David Lounsbury &lt;david.lounsbury@einsteinmed.edu&gt;<br>
<b>Subject:</b> Re: Issues within Green county <o:p></o:p></span></p>

<p class=MsoNormal><o:p>&nbsp;</o:p></p>



CAUTION: This   email comes from an external source; the attachments and/or links may   compromise our secure environment. Do not open or click on suspicious emails.   Please click on the “Phish Alert” button on the top right of the Outlook   dashboard to report any suspicious emails.
--




<p class=MsoNormal style='margin-bottom:12.0pt'><span style='font-size:11.0pt;
font-family:"Arial",sans-serif;mso-fareast-font-family:"Times New Roman";
color:black'>Yeah. This is the same issue that's been reported quite a few
times. The fact of the matter is that at one point, they created a measure. We
have since disallowed that capability and the measure they created is not in
the list options for that type of measure. <o:p></o:p></span></p>

<p class=MsoNormal style='margin-bottom:12.0pt'><span style='font-size:11.0pt;
font-family:"Arial",sans-serif;mso-fareast-font-family:"Times New Roman";
color:black'>The best way to fix this is to add the measures for that strategy
to the list options. They should match exactly. <o:p></o:p></span></p>

<p class=MsoNormal><span style='font-size:11.0pt;font-family:"Arial",sans-serif;
mso-fareast-font-family:"Times New Roman";color:black'>This error should never
appear in wave 2 because you're never allowing them to enter their own
measures. <o:p></o:p></span></p>

<p class=MsoNormal style='margin-bottom:12.0pt'><span style='font-size:11.0pt;
font-family:"Arial",sans-serif;mso-fareast-font-family:"Times New Roman";
color:black'></span><br>
<span id=ms-outlook-android-cursor><br style='mso-special-character:line-break'>
<![if !supportLineBreakNewLine]><br style='mso-special-character:line-break'>
<![endif]><o:p></o:p></span></p>

<div class=MsoNormal align=center style='text-align:center'><span
style='mso-fareast-font-family:"Times New Roman"'>

<hr size=3 width="98%" align=center>

</span></div>

<p class=MsoNormal style='mso-outline-level:1'><b><span style='font-size:11.0pt;
font-family:"Calibri",sans-serif;mso-fareast-font-family:"Times New Roman";
color:black'>From:</span></b><span style='font-size:11.0pt;font-family:"Calibri",sans-serif;
mso-fareast-font-family:"Times New Roman";color:black'> Donrie Purcell &lt;<a
href="mailto:donrie.purcell@einsteinmed.edu">donrie.purcell@einsteinmed.edu</a>&gt;<br>
<b>Sent:</b> Wednesday, January 12, 2022 3:17:25 PM<br>
<b>To:</b> Jeff Bazinet &lt;<a href="mailto:jbazinet@northcountryinitiative.org">jbazinet@northcountryinitiative.org</a>&gt;<br>
<b>Cc:</b> David Lounsbury &lt;<a href="mailto:david.lounsbury@einsteinmed.edu">david.lounsbury@einsteinmed.edu</a>&gt;<br>
<b>Subject:</b> Issues within Green county </span><span style='mso-fareast-font-family:
"Times New Roman"'><o:p></o:p></span></p>

<p class=MsoNormal><span style='mso-fareast-font-family:"Times New Roman"'>&nbsp;<o:p></o:p></span></p>

<h4><span style='mso-fareast-font-family:"Times New Roman";color:red'>This
Message is being sent from outside of FDRHPO or NCI.&nbsp; Please do not click
on links or download attachments without properly verifying them.&nbsp;&nbsp;</span><span
style='mso-fareast-font-family:"Times New Roman"'><o:p></o:p></span></h4>

<p class=xmsonormal>&nbsp;<o:p></o:p></p>

<p>&nbsp;<o:p></o:p></p>

<p class=xmsonormal><span style='font-size:12.0pt;font-family:"Times New Roman",serif'>Hi
Jeff</span><o:p></o:p></p>

<p class=xmsonormal><span style='font-size:12.0pt;font-family:"Times New Roman",serif'>&nbsp;</span><o:p></o:p></p>

<p class=xmsonormal><span style='font-size:12.0pt;font-family:"Times New Roman",serif'>Jessica
has reported that her team at Green County has not been able to effectively
edit Measures in Specification.</span><o:p></o:p></p>

<p class=xmsonormal><span style='font-size:12.0pt;font-family:"Times New Roman",serif'>&nbsp;</span><o:p></o:p></p>

<p class=xmsonormal><span style='font-size:12.0pt;font-family:"Times New Roman",serif'>I
have placed an error code in the email for you to review.</span><o:p></o:p></p>

<p class=xmsonormal><span style='font-size:12.0pt;font-family:"Times New Roman",serif'>&nbsp;</span><o:p></o:p></p>

<p class=xmsonormal><span style='font-size:12.0pt;font-family:"Times New Roman",serif'>&nbsp;</span><o:p></o:p></p>

<p class=xmsonormal><span style='font-size:12.0pt;font-family:"Times New Roman",serif'><![if !vml]><img border=0 width=767 height=342
src="file:///C:/Users/dlounsbu/AppData/Local/Temp/msohtmlclip1/01/clip_image002.png"
style='height:3.562in;width:7.989in'
alt="Graphical user interface, text, application, email&#10;&#10;Description automatically generated"
v:shapes="x_Picture_x0020_1"><![endif]></span><o:p></o:p></p>

<p class=xmsonormal><span style='font-size:12.0pt;font-family:"Times New Roman",serif'>&nbsp;</span><o:p></o:p></p>

<p class=xmsonormal style='vertical-align:baseline'><span style='font-size:
12.0pt;font-family:"Times New Roman",serif;color:black'>Regards<br>
Donrie Purcell, PhD, MPH</span><o:p></o:p></p>

<p class=xmsonormal style='vertical-align:baseline'><span style='font-size:
12.0pt;font-family:"Times New Roman",serif;color:black'>&nbsp;</span><o:p></o:p></p>

<span style='font-size:12.0pt;font-family:"Times New Roman",serif;mso-fareast-font-family:
Calibri;mso-fareast-theme-font:minor-latin;color:black;mso-ansi-language:EN-US;
mso-fareast-language:EN-US;mso-bidi-language:AR-SA'>Every generation has the
obligation to free men's minds for a look at new worlds,....to look out from a
higher plateau than the last generation.<br>
Ellison S. Onizuka&nbsp;<br>
<br style='mso-special-character:line-break'>
<![if !supportLineBreakNewLine]><br style='mso-special-character:line-break'>
<![endif]></span>
</body>

</html>

**Comment by dlounsbu** [comment]
> Yeah. This is the same issue that's been reported quite a few times. The fact of the matter is that at one point, they created a measure. We have since disallowed that capability and the measure they created is not in the list options for that type of measure.
> 
> The best way to fix this is to add the measures for that strategy to the list options. They should match exactly.
> 
> This error should never appear in wave 2 because you're never allowing them to enter their own measures.

Thanks for this information. So, we should be able to add the measure they added to the list options, then the issue will go away, Correct?

**Comment by dlounsbu** [comment]
@donriepurcell 

If we Download the Data for Green, I expect that we will see the 'offending' Measure Name, and then we can add it to List Options. I would copy and paste it from the Download (as text), as a new Measures list option. 

Can you give this a shot? 

DL

**Comment by dlounsbu** [comment]
> The offending measure is "2.14 # of naloxone units distributed in community".
> 
> While this measure exists in the database, it is there for OEND, not MOUD, which is how their strategy has been defined..

Thank you @jbazinet1111 

@donriepurcell  Can you follow up with Greene County about this next week? 

@donriepurcell  We should not have these issues with Wave 2 if we have a clean, compete codebook of measures, and if we can effectively train users. 

DL

**Comment by donriepurcell** [comment]
Hi Jeff 
Thanks for pointing out the issue previously. It took me a while to figure out that Green county had a strategy that should be in OEND, which was misplaced as an MOUD strategy. 
David and I moved to edit the strategy, and I am closing this service request. 
Regards 
Donrie

**Comment by dlounsbu** [comment]
<html xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:w="urn:schemas-microsoft-com:office:word"
xmlns:m="http://schemas.microsoft.com/office/2004/12/omml"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Word.Document>
<meta name=Generator content="Microsoft Word 15">
<meta name=Originator content="Microsoft Word 15">
<link rel=File-List
href="file:///C:/Users/dlounsbu/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">

<link rel=themeData
href="file:///C:/Users/dlounsbu/AppData/Local/Temp/msohtmlclip1/01/clip_themedata.thmx">
<link rel=colorSchemeMapping
href="file:///C:/Users/dlounsbu/AppData/Local/Temp/msohtmlclip1/01/clip_colorschememapping.xml">

<style>

</style>

</head>

<body lang=EN-US link=blue vlink="#954F72" style='tab-interval:.5in'>


<p class=MsoNormal><span style='font-size:11.0pt;font-family:"Calibri",sans-serif;
mso-ascii-theme-font:minor-latin;mso-hansi-theme-font:minor-latin;mso-bidi-font-family:
"Times New Roman";mso-bidi-theme-font:minor-bidi;color:#1F497D'><o:p>&nbsp;</o:p></span></p>

<p class=MsoNormal><b><span style='font-size:11.0pt;font-family:"Calibri",sans-serif;
mso-fareast-font-family:"Times New Roman"'>From:</span></b><span
style='font-size:11.0pt;font-family:"Calibri",sans-serif;mso-fareast-font-family:
"Times New Roman"'> Jessica Neufeld [mailto:jn2434@columbia.edu] <br>
<b>Sent:</b> Thursday, January 27, 2022 5:27 PM<br>
<b>To:</b> Donrie Purcell &lt;donrie.purcell@einsteinmed.edu&gt;<br>
<b>Cc:</b> David Lounsbury &lt;david.lounsbury@einsteinmed.edu&gt;<br>
<b>Subject:</b> Re: Green County<o:p></o:p></span></p>

<p class=MsoNormal><o:p>&nbsp;</o:p></p>



CAUTION: This   email comes from an external source; the attachments and/or links may   compromise our secure environment. Do not open or click on suspicious emails.   Please click on the “Phish Alert” button on the top right of the Outlook   dashboard to report any suspicious emails.
--




<p class=MsoNormal><span style='mso-fareast-font-family:"Times New Roman"'>Hi
Donrie,&nbsp; <o:p></o:p></span></p>

<p class=MsoNormal><span style='mso-fareast-font-family:"Times New Roman"'>Thanks
for getting back to me.&nbsp;<o:p></o:p></span></p>

<p class=MsoNormal><span style='mso-fareast-font-family:"Times New Roman"'><o:p>&nbsp;</o:p></span></p>

<p class=MsoNormal><span style='mso-fareast-font-family:"Times New Roman"'>So,
because&nbsp;the ORCCA bucket&nbsp;was mislabeled, it prevented editing from
happening to the measures?&nbsp;<o:p></o:p></span></p>

<p class=MsoNormal><span style='mso-fareast-font-family:"Times New Roman"'>I
feel like I haven't come across that issue before. Do you think it's specific
to Greene or has the potential to be an issue with all the counties?&nbsp;<o:p></o:p></span></p>

<p class=MsoNormal><span style='mso-fareast-font-family:"Times New Roman"'><o:p>&nbsp;</o:p></span></p>

<p class=MsoNormal><span style='mso-fareast-font-family:"Times New Roman"'>Best,<o:p></o:p></span></p>

<p class=MsoNormal><span style='mso-fareast-font-family:"Times New Roman"'>Jessica&nbsp;<o:p></o:p></span></p>

<p class=MsoNormal><span style='mso-fareast-font-family:"Times New Roman"'><o:p>&nbsp;</o:p></span></p>

<p class=MsoNormal><span style='mso-fareast-font-family:"Times New Roman"'>On
Wed, Jan 26, 2022 at 3:52 PM Donrie Purcell &lt;<a
href="mailto:donrie.purcell@einsteinmed.edu">donrie.purcell@einsteinmed.edu</a>&gt;
wrote:<o:p></o:p></span></p>

<p class=MsoNormal style='mso-margin-top-alt:auto;mso-margin-bottom-alt:auto'>Hi
Jessica,<o:p></o:p></p>

<p class=MsoNormal style='mso-margin-top-alt:auto;mso-margin-bottom-alt:auto'>&nbsp;<o:p></o:p></p>

<p class=MsoNormal style='mso-margin-top-alt:auto;mso-margin-bottom-alt:auto'>I
want to apologize for taking some time to get back to you as it relates to
editing the IPA strategy within Green County.<o:p></o:p></p>

<p class=MsoNormal style='mso-margin-top-alt:auto;mso-margin-bottom-alt:auto'>It
appears from our discovery that the strategy in question was mislabeled as a
MOUD in the ORCCA EPB &amp; EPB.<o:p></o:p></p>

<p class=MsoNormal style='mso-margin-top-alt:auto;mso-margin-bottom-alt:auto'>I
have attached a series of photos to indicate what was there previous to our
final change.<o:p></o:p></p>

<p class=MsoNormal style='mso-margin-top-alt:auto;mso-margin-bottom-alt:auto'>&nbsp;<o:p></o:p></p>

<p class=MsoNormal style='mso-margin-top-alt:auto;mso-margin-bottom-alt:auto'>&nbsp;<o:p></o:p></p>

<p class=MsoNormal style='mso-margin-top-alt:auto;mso-margin-bottom-alt:auto;
vertical-align:baseline'><span style='color:black'>Regards<br>
Donrie Purcell, PhD, MPH</span><o:p></o:p></p>

<p class=MsoNormal style='mso-margin-top-alt:auto;mso-margin-bottom-alt:auto;
vertical-align:baseline'><span style='color:black'>&nbsp;</span><o:p></o:p></p>


</body>

</html>
