### ISSUE TITLE
Service Request by David Lounsbury - Tracker Download

### ISSUE THREAD

**Issue by dlounsbu** [dlounsbu/NYHEALing-IPAtracker-support#89]
- [ ] Problem NOT RESOLVED
- [ ] Problem PARTIALLY RESOLVED 
- [ ] Problem FULLY RESOLVED and Issue is Closed
- [ ] Qualtrics Post-Service Request Survey was sent to User

Use comments feature (below) to document:

1. A clear and concise description of the solution.

2. A clear and concise description of any alternative solutions or features you've considered.

3. Any additional context, such as screenshots about the problem.

**Comment by dlounsbu** [comment]
@jbazinet1111 

Please check the Data Download feature.

It seems that the download filters are not working consistently.

When I try to download all data (each county checked, all IPA/Strategies, all components), I get some, but not all the requested data.  

[DownloadIPAData_20220316 (2).csv](https://github.com/dlounsbu/NYHEALing-IPAtracker-support/files/8267068/DownloadIPAData_20220316.2.csv)
[DownloadIPAData_20220316 (1).csv](https://github.com/dlounsbu/NYHEALing-IPAtracker-support/files/8267069/DownloadIPAData_20220316.1.csv)
[DownloadIPAData_20220316.csv](https://github.com/dlounsbu/NYHEALing-IPAtracker-support/files/8267072/DownloadIPAData_20220316.csv)

What would be causing this? Is the the Tracker or is this some compatibility thing with the browser? I am using Chrome.

Thanks,
DL
